#include"key.h"
extern flag_ds;
extern miao,fen,shi;
extern day,week,moth,year;
void di()
{
  beep=0;
  delay(50);
  beep=1;
}
void diii()
{
  delay(500);
  beep=0;
  delay(300);
  beep=1;
  delay(300) ;
  beep=0;
  delay(300);
  beep=1;
  delay(300);
  beep=0;
  delay(300);
  beep=1; 
}
void keyscan()
{
   static int flag=0,flag_ymd=0;
   if(s1==0)  //功能键s1  
   {
       delay(10);
	 if(s1==0)
	 {
	        while(!s1);	
	        flag++;
			di();
	   	    if(flag==1)
	    	{
		 		flag_ds=1;
		 		write_com(0x80+0x40+10);
		 		write_com(0x0f);
				diii();
			}
	    	if(flag==2)
	    	{
	      		 write_com(0x80+0x40+7);
		   	}
	   		if(flag==3)
	    	{
	      		 write_com(0x80+0x40+4);
	    	}
			if(flag==4)//week
			{			 			    
				write_com(0x80+12);
				flag_ymd=1;
			}
			if(flag==5)	//day
			{			 			    
				write_com(0x80+9);
				flag_ymd=2;
			}
			if(flag==6)	//moth
			{			 			    
				write_com(0x80+6);
				flag_ymd=3;
			}
			if(flag==7)	 //year
			{			 			    
				write_com(0x80+3);
				flag_ymd=4;
			}
	    	if(flag==8)
	    	{
		   		diii();
		  		flag=0;
		  		flag_ds=0;
				flag_ymd=0;
				write_com(0x0c);
		  		write_ds(0,miao);
		  		write_ds(2,fen);
		  		write_ds(4,shi);
				write_ds(6,week);
				write_ds(7,day);
				write_ds(8,moth);
				write_ds(9,year);
			}
	 } 
   }
   if(flag!=0)
   {
       if(s2==0)	 //加数键s2	   加数键s2		加数键s2	 加数键s2
	 {
	     delay(5);
	     if(s2==0)
	     {
	        while(!s2);
			 di();
		   if(flag_ymd==0)
		   {
		   /*****************************/
		   if(flag==1)
		   {
		        miao++;
			  if(miao==60)
			  {
			       miao=0;
			  }
			  write_time(10,miao,2);
			  write_com(0x80+0x40+10);
		   }
		   if(flag==2)
		   {
		        fen++;
			  if(fen==60)
			  {
			       fen=0;
			  }
			  write_time(7,fen,2);
			  write_com(0x80+0x40+7);
		   }
		   if(flag==3)
		   {
		        shi++;
			  if(shi==24)
			  {
			       shi=0;
			  }
			  write_time(4,shi,2);
			  write_com(0x80+0x40+4);
		   }
		   /**************************/
		   }
		   if(flag_ymd==1)
		   {
		      week++;
			  if(week==8)
			  {
			     week=1;
			  }
			  write_week(week);
			  write_com(0x80+12);
		   }
		   if(flag_ymd==2)
		   {
		      day++;
			  if(day==32)
			  {
			     day=1;
			  }
			  write_time(9,day,1);
			  write_com(0x80+9);
		   }
		   if(flag_ymd==3)
		   {
		      moth++;
			  if(moth==13)
			  {
			     moth=1;
			  }
			  write_time(6,moth,1);
			  write_com(0x80+6);
		   }
		   if(flag_ymd==4)
		   {
		      year++;
			  if(year==30)
			  {
			     year=1;
			  }
			  write_time(3,year,1);
			  write_com(0x80+3);
		   }
	     }
	 }  //加数
	  if(s3==0)	 //减数键s3	   减数键s3		减数键s3	 减数键s3
	 {
	     delay(5);
	     if(s3==0)
	     {
	         while(!s3);
			 di();
		   if(flag_ymd==0)
           {
			/*************************************/
		   if(flag==1)
		   {
		        miao--;
			  if(miao==60||miao<0)
			  {
			       miao=0;
			  }
			  write_time(10,miao,2);
			  write_com(0x80+0x40+10);
		   }
		   if(flag==2)
		   {
		        fen--;
			  if(fen==60||fen<0)
			  {
			       fen=0;
			  }
			  write_time(7,fen,2);
			  write_com(0x80+0x40+7);
		   }
		   if(flag==3)
		   {
		        shi--;
			  if(shi==24||shi<0)
			  {
			       shi=0;
			  }
			  write_time(4,shi,2);
			  write_com(0x80+0x40+4);
		   }
		   /*******************************************/
		   }
		   if(flag_ymd==1)
		   {
		      week--;
			  if(week==0)
			  {
			     week=7;
			  }
			  write_week(week);
			  write_com(0x80+12);
		   }
		   if(flag_ymd==2)
		   {
		      day--;
			  if(day==0)
			  {
			     day=31;
			  }
			  write_time(9,day,1);
			  write_com(0x80+9);
		   }
		   if(flag_ymd==3)
		   {
		      moth--;
			  if(moth==0)
			  {
			     moth=12;
			  }
			  write_time(6,moth,1);
			  write_com(0x80+6);
		   }
		   if(flag_ymd==4)
		   {
		      year--;
			  if(year==0)
			  {
			     year=30;
			  }
			  write_time(3,year,1);
			  write_com(0x80+3);
		   }
	     }
	 }  //减数	   
	  
   }   
}